name: Keep Render Apps Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: curl -s -o /dev/null https://vertualassistantbackend.onrender.com

      - name: Ping Frontend
        run: curl -s -o /dev/null https://virtualassistantbyjayptl.onrender.com
